### ISSUE TITLE
Check the assignment

### ISSUE THREAD

**Issue by AlekseiILitvinov** [AlekseiILitvinov/Week1HomeworkSportmaster#1]
The assignment was to write a program calculating the membership bonuses awarded for a purchase based on the total sum of the previous purchases.
I took liberty of adding some of the other features of the membership terms to the program, as such:
- Upgrade of membership level upon reaching the specified thresholds
- Announce the new bonus multiplier
- Warn of the initial threshold of 1 rouble for membership activation
- Update the total sum in the end of operation, simulating the update to the customer's account

I hope it doesn't overburden the code too much.

**Comment by coursar** [comment]
Пофиксить #2, #3
