### ISSUE TITLE
По всей программе: вынести границы (15_000, 150_000) и т.д. в переменные. Не нужно их повторять по несколько раз

### ISSUE THREAD

**Issue by coursar** [AlekseiILitvinov/Week1HomeworkSportmaster#2]
https://github.com/AlekseiILitvinov/Week1HomeworkSportmaster/blob/7910d7508c76100f2877697fe46213688cd26208/src/Main.java#L31-L36

**Comment by AlekseiILitvinov** [comment]
Fixed - extracted to variables.
