### ISSUE TITLE
Не увидел расчёта итогового бонуса, только multiplier

### ISSUE THREAD

**Issue by coursar** [AlekseiILitvinov/Week1HomeworkSportmaster#3]
https://github.com/AlekseiILitvinov/Week1HomeworkSportmaster/blob/7910d7508c76100f2877697fe46213688cd26208/src/Main.java#L31-L37

**Comment by AlekseiILitvinov** [comment]
Fixed - added explicit calculation. Before it was done on the go inside the "sout" statement.
