### ISSUE TITLE
Переменные нужно объявлять ближе к точке использования

### ISSUE THREAD

**Issue by coursar** [AlekseiILitvinov/Week1HomeworkSportmaster#5]
https://github.com/AlekseiILitvinov/Week1HomeworkSportmaster/blob/9b5a0b87a784e44faf52641396fb9e0b685d4eeb/src/Main.java#L12-L13

Эти должны быть объявлены рядом с `do`

**Comment by AlekseiILitvinov** [comment]
Can't do - I receive the values from the user inside the do-while loop. I can't declare the variables there, because they would be in the wrong _scope_. Of course, I can abandon the user input all along.
I've moved the declaration of the `bonusAwarded` variable closer to the assignment statement.

**Comment by AlekseiILitvinov** [comment]
Oh, I see - before the `do`, not inside. OK, done.
